# BEGIN_KITTY_THEME
window_padding_width 0
font_family FiraCode Nerd Font
font_size 18
background_opacity 0.80
dynamic_background_opacity yes
disable_ligatures never
shell tmux new-session -A -s base
# Black Metal
include current-theme.conf

