# file: ~/.config/tmux-sessionizer/tmux-sessionizer.conf

# Add your common directories to search paths
TS_EXTRA_SEARCH_PATHS=(
    "$HOME/notes:2"
    "$HOME/python:1"
    "$HOME/java:1"
    "$HOME/elixir:1"
)
TS_MAX_DEPTH=1
