set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g status-position top
set -g status-style "bg=default bold"
set -g window-status-current-style "fg=red bold"
set -g status-right ""
set -sg escape-time 0

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/todo.md"

bind-key -n C-f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"
bind-key Tab last-window

bind r source-file ~/.tmux.conf \; display-message "reloaded"
bind L run-shell "~/.local/bin/tmux-sessionizer $HOME/notes"
bind K run-shell "~/.local/bin/tmux-sessionizer $HOME/python"
bind J run-shell "~/.local/bin/tmux-sessionizer $HOME/java"
bind C run-shell "~/.local/bin/tmux-sessionizer $HOME/.config"
bind H run-shell "~/.local/bin/tmux-sessionizer base"
